// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaspberryPi.API.Database;

#nullable disable

namespace RaspberryPi.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241221171506_AddNameToWeekSchedule")]
    partial class AddNameToWeekSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RaspberryPi.API.Entities.WeekSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Second")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeekSchedule", t =>
                        {
                            t.HasCheckConstraint("CK_WeekSchedule_Day_Range", "Day BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_WeekSchedule_Hour_Range", "Hour BETWEEN 0 AND 23");

                            t.HasCheckConstraint("CK_WeekSchedule_Minute_Range", "Minute BETWEEN 0 AND 59");

                            t.HasCheckConstraint("CK_WeekSchedule_Second_Range", "Second BETWEEN 0 AND 59");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
